defaultContentLanguage = "en"
title = "MomCorp"
theme = "ananke"


[params]
  featured_image = "/images/ConquerEarthYou.jpg"
  custom_css = ["css/styles.css"]
[menu]

  [[menu.main]]
    identifier = "wiki"
    name = "Wiki"
    url = "https://futurama.fandom.com/wiki/MomCorp"

[taxonomies]
  hability = "habilities"
  tag = "tags"

[languages]
  [languages.en]
    weight = 1
    contentDir = "content/en-EN"
    baseURL = "http://example.com/"
    languageCode = "en-EN"
    languageName = "English"
  [languages.es]
    weight = 2
    contentDir = "content/es-ES"
    title = "Corporación Mamá"
    baseURL = "http://example.es"
    languageCode = "es-ES"
    languageName = "Español"
    [languages.es.taxonomies]
      habilidad = "habilidades"
      tag = "tags"
    [[languages.es.menu.main]]
      url = "https://futurama.fandom.com/es/wiki/Mam%C3%A1"
      name = "Wiki"
      identifier = "wiki"