baseURL = "http://example.org/"
languageCode = "en-us"
title = "MomCorp"
theme = "ananke"


[params]
  featured_image = "/images/ConquerEarthYou.jpg"
  custom_css = ["css/styles.css"]
[menu]

  [[menu.main]]
    identifier = "wiki"
    name = "Wiki"
    url = "https://futurama.fandom.com/wiki/MomCorp"

[taxonomies]
  hability = "habilities"
  tag = "tags"