[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.58.3"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://momcorp.netlify.com/"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_ENABLEGITINFO = "true"
